# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-08 12:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20160808_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 8, 12, 30, 28, 523744, tzinfo=utc)),
        ),
    ]
