# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-08 12:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20160808_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 8, 12, 38, 3, 409762, tzinfo=utc)),
        ),
    ]
